// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: pb.proto

package pbpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArgs) Reset() {
	*x = GetArgs{}
	mi := &file_pb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArgs) ProtoMessage() {}

func (x *GetArgs) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArgs.ProtoReflect.Descriptor instead.
func (*GetArgs) Descriptor() ([]byte, []int) {
	return file_pb_proto_rawDescGZIP(), []int{0}
}

func (x *GetArgs) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Err           string                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"` // Used to return errors like "ErrNoKey" or "ErrWrongServer"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReply) Reset() {
	*x = GetReply{}
	mi := &file_pb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReply) ProtoMessage() {}

func (x *GetReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReply.ProtoReflect.Descriptor instead.
func (*GetReply) Descriptor() ([]byte, []int) {
	return file_pb_proto_rawDescGZIP(), []int{1}
}

func (x *GetReply) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type PutAppendArgs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Op    string                 `protobuf:"bytes,3,opt,name=op,proto3" json:"op,omitempty"` // "Put" or "Append"
	// Essential for exactly-once semantics to prevent duplicate writes on retry
	ClientId      int64 `protobuf:"varint,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	SeqNum        int64 `protobuf:"varint,5,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutAppendArgs) Reset() {
	*x = PutAppendArgs{}
	mi := &file_pb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutAppendArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutAppendArgs) ProtoMessage() {}

func (x *PutAppendArgs) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutAppendArgs.ProtoReflect.Descriptor instead.
func (*PutAppendArgs) Descriptor() ([]byte, []int) {
	return file_pb_proto_rawDescGZIP(), []int{2}
}

func (x *PutAppendArgs) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutAppendArgs) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PutAppendArgs) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *PutAppendArgs) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *PutAppendArgs) GetSeqNum() int64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

type PutAppendReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           string                 `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutAppendReply) Reset() {
	*x = PutAppendReply{}
	mi := &file_pb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutAppendReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutAppendReply) ProtoMessage() {}

func (x *PutAppendReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutAppendReply.ProtoReflect.Descriptor instead.
func (*PutAppendReply) Descriptor() ([]byte, []int) {
	return file_pb_proto_rawDescGZIP(), []int{3}
}

func (x *PutAppendReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

// You can often reuse PutAppendArgs for forwarding, but defining a specific
// message is cleaner if you need to pass additional internal state.
type ForwardArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Args          *PutAppendArgs         `protobuf:"bytes,1,opt,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardArgs) Reset() {
	*x = ForwardArgs{}
	mi := &file_pb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardArgs) ProtoMessage() {}

func (x *ForwardArgs) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardArgs.ProtoReflect.Descriptor instead.
func (*ForwardArgs) Descriptor() ([]byte, []int) {
	return file_pb_proto_rawDescGZIP(), []int{4}
}

func (x *ForwardArgs) GetArgs() *PutAppendArgs {
	if x != nil {
		return x.Args
	}
	return nil
}

type ForwardReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           string                 `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardReply) Reset() {
	*x = ForwardReply{}
	mi := &file_pb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardReply) ProtoMessage() {}

func (x *ForwardReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardReply.ProtoReflect.Descriptor instead.
func (*ForwardReply) Descriptor() ([]byte, []int) {
	return file_pb_proto_rawDescGZIP(), []int{5}
}

func (x *ForwardReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type TransferStateArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         map[string]string      `protobuf:"bytes,1,rep,name=state,proto3" json:"state,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferStateArgs) Reset() {
	*x = TransferStateArgs{}
	mi := &file_pb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferStateArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferStateArgs) ProtoMessage() {}

func (x *TransferStateArgs) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferStateArgs.ProtoReflect.Descriptor instead.
func (*TransferStateArgs) Descriptor() ([]byte, []int) {
	return file_pb_proto_rawDescGZIP(), []int{6}
}

func (x *TransferStateArgs) GetState() map[string]string {
	if x != nil {
		return x.State
	}
	return nil
}

type TransferStateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         map[string]string      `protobuf:"bytes,1,rep,name=state,proto3" json:"state,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Transfers the entire KV store
	Err           string                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferStateReply) Reset() {
	*x = TransferStateReply{}
	mi := &file_pb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferStateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferStateReply) ProtoMessage() {}

func (x *TransferStateReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferStateReply.ProtoReflect.Descriptor instead.
func (*TransferStateReply) Descriptor() ([]byte, []int) {
	return file_pb_proto_rawDescGZIP(), []int{7}
}

func (x *TransferStateReply) GetState() map[string]string {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *TransferStateReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_pb_proto protoreflect.FileDescriptor

const file_pb_proto_rawDesc = "" +
	"\n" +
	"\bpb.proto\x12\x02pb\"\x1b\n" +
	"\aGetArgs\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"2\n" +
	"\bGetReply\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x10\n" +
	"\x03err\x18\x02 \x01(\tR\x03err\"}\n" +
	"\rPutAppendArgs\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x0e\n" +
	"\x02op\x18\x03 \x01(\tR\x02op\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\x03R\bclientId\x12\x17\n" +
	"\aseq_num\x18\x05 \x01(\x03R\x06seqNum\"\"\n" +
	"\x0ePutAppendReply\x12\x10\n" +
	"\x03err\x18\x01 \x01(\tR\x03err\"4\n" +
	"\vForwardArgs\x12%\n" +
	"\x04args\x18\x01 \x01(\v2\x11.pb.PutAppendArgsR\x04args\" \n" +
	"\fForwardReply\x12\x10\n" +
	"\x03err\x18\x01 \x01(\tR\x03err\"\x85\x01\n" +
	"\x11TransferStateArgs\x126\n" +
	"\x05state\x18\x01 \x03(\v2 .pb.TransferStateArgs.StateEntryR\x05state\x1a8\n" +
	"\n" +
	"StateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x99\x01\n" +
	"\x12TransferStateReply\x127\n" +
	"\x05state\x18\x01 \x03(\v2!.pb.TransferStateReply.StateEntryR\x05state\x12\x10\n" +
	"\x03err\x18\x02 \x01(\tR\x03err\x1a8\n" +
	"\n" +
	"StateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xcf\x01\n" +
	"\tPBService\x12 \n" +
	"\x03Get\x12\v.pb.GetArgs\x1a\f.pb.GetReply\x122\n" +
	"\tPutAppend\x12\x11.pb.PutAppendArgs\x1a\x12.pb.PutAppendReply\x12,\n" +
	"\aForward\x12\x0f.pb.ForwardArgs\x1a\x10.pb.ForwardReply\x12>\n" +
	"\rTransferState\x12\x15.pb.TransferStateArgs\x1a\x16.pb.TransferStateReplyB3Z1github.com/hollinsStuart/pb-kv-service/proto/pbpbb\x06proto3"

var (
	file_pb_proto_rawDescOnce sync.Once
	file_pb_proto_rawDescData []byte
)

func file_pb_proto_rawDescGZIP() []byte {
	file_pb_proto_rawDescOnce.Do(func() {
		file_pb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_proto_rawDesc), len(file_pb_proto_rawDesc)))
	})
	return file_pb_proto_rawDescData
}

var file_pb_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pb_proto_goTypes = []any{
	(*GetArgs)(nil),            // 0: pb.GetArgs
	(*GetReply)(nil),           // 1: pb.GetReply
	(*PutAppendArgs)(nil),      // 2: pb.PutAppendArgs
	(*PutAppendReply)(nil),     // 3: pb.PutAppendReply
	(*ForwardArgs)(nil),        // 4: pb.ForwardArgs
	(*ForwardReply)(nil),       // 5: pb.ForwardReply
	(*TransferStateArgs)(nil),  // 6: pb.TransferStateArgs
	(*TransferStateReply)(nil), // 7: pb.TransferStateReply
	nil,                        // 8: pb.TransferStateArgs.StateEntry
	nil,                        // 9: pb.TransferStateReply.StateEntry
}
var file_pb_proto_depIdxs = []int32{
	2, // 0: pb.ForwardArgs.args:type_name -> pb.PutAppendArgs
	8, // 1: pb.TransferStateArgs.state:type_name -> pb.TransferStateArgs.StateEntry
	9, // 2: pb.TransferStateReply.state:type_name -> pb.TransferStateReply.StateEntry
	0, // 3: pb.PBService.Get:input_type -> pb.GetArgs
	2, // 4: pb.PBService.PutAppend:input_type -> pb.PutAppendArgs
	4, // 5: pb.PBService.Forward:input_type -> pb.ForwardArgs
	6, // 6: pb.PBService.TransferState:input_type -> pb.TransferStateArgs
	1, // 7: pb.PBService.Get:output_type -> pb.GetReply
	3, // 8: pb.PBService.PutAppend:output_type -> pb.PutAppendReply
	5, // 9: pb.PBService.Forward:output_type -> pb.ForwardReply
	7, // 10: pb.PBService.TransferState:output_type -> pb.TransferStateReply
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_proto_init() }
func file_pb_proto_init() {
	if File_pb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_proto_rawDesc), len(file_pb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_proto_goTypes,
		DependencyIndexes: file_pb_proto_depIdxs,
		MessageInfos:      file_pb_proto_msgTypes,
	}.Build()
	File_pb_proto = out.File
	file_pb_proto_goTypes = nil
	file_pb_proto_depIdxs = nil
}
