// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: pb.proto

package pbpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PBService_Get_FullMethodName           = "/pb.PBService/Get"
	PBService_PutAppend_FullMethodName     = "/pb.PBService/PutAppend"
	PBService_Forward_FullMethodName       = "/pb.PBService/Forward"
	PBService_TransferState_FullMethodName = "/pb.PBService/TransferState"
)

// PBServiceClient is the client API for PBService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PBServiceClient interface {
	// Client-facing RPCs
	Get(ctx context.Context, in *GetArgs, opts ...grpc.CallOption) (*GetReply, error)
	PutAppend(ctx context.Context, in *PutAppendArgs, opts ...grpc.CallOption) (*PutAppendReply, error)
	// Internal node-to-node RPCs
	Forward(ctx context.Context, in *ForwardArgs, opts ...grpc.CallOption) (*ForwardReply, error)
	TransferState(ctx context.Context, in *TransferStateArgs, opts ...grpc.CallOption) (*TransferStateReply, error)
}

type pBServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPBServiceClient(cc grpc.ClientConnInterface) PBServiceClient {
	return &pBServiceClient{cc}
}

func (c *pBServiceClient) Get(ctx context.Context, in *GetArgs, opts ...grpc.CallOption) (*GetReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReply)
	err := c.cc.Invoke(ctx, PBService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pBServiceClient) PutAppend(ctx context.Context, in *PutAppendArgs, opts ...grpc.CallOption) (*PutAppendReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutAppendReply)
	err := c.cc.Invoke(ctx, PBService_PutAppend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pBServiceClient) Forward(ctx context.Context, in *ForwardArgs, opts ...grpc.CallOption) (*ForwardReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardReply)
	err := c.cc.Invoke(ctx, PBService_Forward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pBServiceClient) TransferState(ctx context.Context, in *TransferStateArgs, opts ...grpc.CallOption) (*TransferStateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferStateReply)
	err := c.cc.Invoke(ctx, PBService_TransferState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PBServiceServer is the server API for PBService service.
// All implementations must embed UnimplementedPBServiceServer
// for forward compatibility.
type PBServiceServer interface {
	// Client-facing RPCs
	Get(context.Context, *GetArgs) (*GetReply, error)
	PutAppend(context.Context, *PutAppendArgs) (*PutAppendReply, error)
	// Internal node-to-node RPCs
	Forward(context.Context, *ForwardArgs) (*ForwardReply, error)
	TransferState(context.Context, *TransferStateArgs) (*TransferStateReply, error)
	mustEmbedUnimplementedPBServiceServer()
}

// UnimplementedPBServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPBServiceServer struct{}

func (UnimplementedPBServiceServer) Get(context.Context, *GetArgs) (*GetReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedPBServiceServer) PutAppend(context.Context, *PutAppendArgs) (*PutAppendReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PutAppend not implemented")
}
func (UnimplementedPBServiceServer) Forward(context.Context, *ForwardArgs) (*ForwardReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Forward not implemented")
}
func (UnimplementedPBServiceServer) TransferState(context.Context, *TransferStateArgs) (*TransferStateReply, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferState not implemented")
}
func (UnimplementedPBServiceServer) mustEmbedUnimplementedPBServiceServer() {}
func (UnimplementedPBServiceServer) testEmbeddedByValue()                   {}

// UnsafePBServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PBServiceServer will
// result in compilation errors.
type UnsafePBServiceServer interface {
	mustEmbedUnimplementedPBServiceServer()
}

func RegisterPBServiceServer(s grpc.ServiceRegistrar, srv PBServiceServer) {
	// If the following call panics, it indicates UnimplementedPBServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PBService_ServiceDesc, srv)
}

func _PBService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PBServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PBService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PBServiceServer).Get(ctx, req.(*GetArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _PBService_PutAppend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutAppendArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PBServiceServer).PutAppend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PBService_PutAppend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PBServiceServer).PutAppend(ctx, req.(*PutAppendArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _PBService_Forward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PBServiceServer).Forward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PBService_Forward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PBServiceServer).Forward(ctx, req.(*ForwardArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _PBService_TransferState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferStateArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PBServiceServer).TransferState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PBService_TransferState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PBServiceServer).TransferState(ctx, req.(*TransferStateArgs))
	}
	return interceptor(ctx, in, info, handler)
}

// PBService_ServiceDesc is the grpc.ServiceDesc for PBService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PBService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PBService",
	HandlerType: (*PBServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _PBService_Get_Handler,
		},
		{
			MethodName: "PutAppend",
			Handler:    _PBService_PutAppend_Handler,
		},
		{
			MethodName: "Forward",
			Handler:    _PBService_Forward_Handler,
		},
		{
			MethodName: "TransferState",
			Handler:    _PBService_TransferState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb.proto",
}
