// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: view.proto

package viewpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents the current state of the cluster
type View struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewNum       uint64                 `protobuf:"varint,1,opt,name=view_num,json=viewNum,proto3" json:"view_num,omitempty"`
	Primary       string                 `protobuf:"bytes,2,opt,name=primary,proto3" json:"primary,omitempty"` // The network address/ID of the primary node
	Backup        string                 `protobuf:"bytes,3,opt,name=backup,proto3" json:"backup,omitempty"`   // The network address/ID of the backup node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *View) Reset() {
	*x = View{}
	mi := &file_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *View) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*View) ProtoMessage() {}

func (x *View) ProtoReflect() protoreflect.Message {
	mi := &file_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use View.ProtoReflect.Descriptor instead.
func (*View) Descriptor() ([]byte, []int) {
	return file_view_proto_rawDescGZIP(), []int{0}
}

func (x *View) GetViewNum() uint64 {
	if x != nil {
		return x.ViewNum
	}
	return 0
}

func (x *View) GetPrimary() string {
	if x != nil {
		return x.Primary
	}
	return ""
}

func (x *View) GetBackup() string {
	if x != nil {
		return x.Backup
	}
	return ""
}

type PingArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Me            string                 `protobuf:"bytes,1,opt,name=me,proto3" json:"me,omitempty"`                           // The ID of the node sending the ping
	ViewNum       uint64                 `protobuf:"varint,2,opt,name=view_num,json=viewNum,proto3" json:"view_num,omitempty"` // The view number this node currently thinks is active
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingArgs) Reset() {
	*x = PingArgs{}
	mi := &file_view_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingArgs) ProtoMessage() {}

func (x *PingArgs) ProtoReflect() protoreflect.Message {
	mi := &file_view_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingArgs.ProtoReflect.Descriptor instead.
func (*PingArgs) Descriptor() ([]byte, []int) {
	return file_view_proto_rawDescGZIP(), []int{1}
}

func (x *PingArgs) GetMe() string {
	if x != nil {
		return x.Me
	}
	return ""
}

func (x *PingArgs) GetViewNum() uint64 {
	if x != nil {
		return x.ViewNum
	}
	return 0
}

type PingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          *View                  `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReply) Reset() {
	*x = PingReply{}
	mi := &file_view_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReply) ProtoMessage() {}

func (x *PingReply) ProtoReflect() protoreflect.Message {
	mi := &file_view_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReply.ProtoReflect.Descriptor instead.
func (*PingReply) Descriptor() ([]byte, []int) {
	return file_view_proto_rawDescGZIP(), []int{2}
}

func (x *PingReply) GetView() *View {
	if x != nil {
		return x.View
	}
	return nil
}

type GetArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArgs) Reset() {
	*x = GetArgs{}
	mi := &file_view_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArgs) ProtoMessage() {}

func (x *GetArgs) ProtoReflect() protoreflect.Message {
	mi := &file_view_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArgs.ProtoReflect.Descriptor instead.
func (*GetArgs) Descriptor() ([]byte, []int) {
	return file_view_proto_rawDescGZIP(), []int{3}
}

type GetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          *View                  `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReply) Reset() {
	*x = GetReply{}
	mi := &file_view_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReply) ProtoMessage() {}

func (x *GetReply) ProtoReflect() protoreflect.Message {
	mi := &file_view_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReply.ProtoReflect.Descriptor instead.
func (*GetReply) Descriptor() ([]byte, []int) {
	return file_view_proto_rawDescGZIP(), []int{4}
}

func (x *GetReply) GetView() *View {
	if x != nil {
		return x.View
	}
	return nil
}

var File_view_proto protoreflect.FileDescriptor

const file_view_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"view.proto\x12\x04view\"S\n" +
	"\x04View\x12\x19\n" +
	"\bview_num\x18\x01 \x01(\x04R\aviewNum\x12\x18\n" +
	"\aprimary\x18\x02 \x01(\tR\aprimary\x12\x16\n" +
	"\x06backup\x18\x03 \x01(\tR\x06backup\"5\n" +
	"\bPingArgs\x12\x0e\n" +
	"\x02me\x18\x01 \x01(\tR\x02me\x12\x19\n" +
	"\bview_num\x18\x02 \x01(\x04R\aviewNum\"+\n" +
	"\tPingReply\x12\x1e\n" +
	"\x04view\x18\x01 \x01(\v2\n" +
	".view.ViewR\x04view\"\t\n" +
	"\aGetArgs\"*\n" +
	"\bGetReply\x12\x1e\n" +
	"\x04view\x18\x01 \x01(\v2\n" +
	".view.ViewR\x04view2\\\n" +
	"\vViewService\x12'\n" +
	"\x04Ping\x12\x0e.view.PingArgs\x1a\x0f.view.PingReply\x12$\n" +
	"\x03Get\x12\r.view.GetArgs\x1a\x0e.view.GetReplyB\x1cZ\x1apb-kv-service/proto/viewpbb\x06proto3"

var (
	file_view_proto_rawDescOnce sync.Once
	file_view_proto_rawDescData []byte
)

func file_view_proto_rawDescGZIP() []byte {
	file_view_proto_rawDescOnce.Do(func() {
		file_view_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_view_proto_rawDesc), len(file_view_proto_rawDesc)))
	})
	return file_view_proto_rawDescData
}

var file_view_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_view_proto_goTypes = []any{
	(*View)(nil),      // 0: view.View
	(*PingArgs)(nil),  // 1: view.PingArgs
	(*PingReply)(nil), // 2: view.PingReply
	(*GetArgs)(nil),   // 3: view.GetArgs
	(*GetReply)(nil),  // 4: view.GetReply
}
var file_view_proto_depIdxs = []int32{
	0, // 0: view.PingReply.view:type_name -> view.View
	0, // 1: view.GetReply.view:type_name -> view.View
	1, // 2: view.ViewService.Ping:input_type -> view.PingArgs
	3, // 3: view.ViewService.Get:input_type -> view.GetArgs
	2, // 4: view.ViewService.Ping:output_type -> view.PingReply
	4, // 5: view.ViewService.Get:output_type -> view.GetReply
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_view_proto_init() }
func file_view_proto_init() {
	if File_view_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_view_proto_rawDesc), len(file_view_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_view_proto_goTypes,
		DependencyIndexes: file_view_proto_depIdxs,
		MessageInfos:      file_view_proto_msgTypes,
	}.Build()
	File_view_proto = out.File
	file_view_proto_goTypes = nil
	file_view_proto_depIdxs = nil
}
